# Logger configuration
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=n
CONFIG_LOG_BUFFER_SIZE=4096

# GPIO configuration
CONFIG_GPIO=y

# PWM configuration (for status LED PWM if needed)
CONFIG_PWM=y

# Enable Bluetooth Stack & GATT Configs
CONFIG_BT=y
CONFIG_BT_SMP=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="se3dstudio_mic"
CONFIG_BT_DEVICE_APPEARANCE=833

# BLE Throughput and MTU Optimizations
CONFIG_BT_BUF_ACL_TX_SIZE=251
CONFIG_BT_L2CAP_TX_MTU=247
CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_BT_USER_PHY_UPDATE=y
CONFIG_BT_USER_DATA_LEN_UPDATE=y

# Enable Audio & Digital Microphone (DMIC) subsystems for PDM microphone
CONFIG_AUDIO=y
CONFIG_AUDIO_DMIC=y
